BeeQuick/BeeQuick_proj/BeeQuick_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.static import serve

from . import settings
from home_page import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^static/(?P<path>.*)', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^$', views.show_homepage),
    url(r'^homepage/', include('home_page.urls', namespace='home')),
    url(r'^quickbuy/', include('quick_buy.urls', namespace='quickbuy')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^mine/', include('mine.urls', namespace='mine')),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^order/', include('order.urls', namespace='order')),
]

from . import settings

from django.contrib.staticfiles.urls import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BeeQuick/BeeQuick_proj/mine/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^mine/$', views.mine, name='mine'),
]

BeeQuick/BeeQuick_proj/users/urls.py
from django.conf.urls import url
from rest_framework import routers

from . import views

router = routers.SimpleRouter()
router.register(r'checkuser', views.CheckUser)

urlpatterns = [

    url(r'^login/(?P<r_path>.+)', views.login, name='login'),
    url(r'^regist/(.*)', views.regist, name='regist'),
    url(r'^logout/', views.logout, name='logout'),
]

urlpatterns += router.urls

BeeQuick/BeeQuick_proj/users/models.py
from django.db import models


class UserModel(models.Model):

    user_name = models.CharField(max_length=32, unique=True)  # 用户名
    password = models.CharField(max_length=255)  # 密码
    email = models.CharField(max_length=64, unique=True)  # 邮箱
    sex = models.BooleanField(default=False)  # 性别 False代表女
    icon = models.ImageField(upload_to='icons')  # 头像
    is_delete = models.BooleanField(default=False)  # 是否删除

    class Meta:
        db_table = 'tb_users'


class TicketModel(models.Model):

    user = models.ForeignKey(UserModel)
    ticket = models.CharField(max_length=32)
    create_time = models.IntegerField()

    class Meta:
        db_table = 'tb_user_ticket'

BeeQuick/BeeQuick_proj/users/views.py
from django.contrib.auth.hashers import check_password, make_password
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.urlresolvers import reverse
from random import choice
from time import time
from rest_framework import mixins, viewsets
from rest_framework.response import Response

from .models import UserModel, TicketModel
from .serializers import UserSerializer
from .filters import UserFilter


def regist(request, r_path):

    if request.method == 'GET':

        # r_path = request.GET.get('r_path')

        return render(request, 'user/user_register.html', {'r_path': r_path})

    if request.method == 'POST':

        username = request.POST.get('username').strip()
        email = request.POST.get('email').strip()
        password = request.POST.get('password')
        icon = request.FILES.get('icon')
        r_path = request.POST.get('r_path')

        if not username:
            return render(request, 'user/user_register.html', {'name_result': '请输入正确的用户名'})

        user = UserModel.objects.filter(user_name=username)
        if user:
            return render(request, 'user/user_register.html', {'name_result': '用户名已存在'})

        UserModel.objects.create(
            user_name=username,
            email=email,
            password=make_password(password),
            icon=icon,
        )
        r_path = r_path if r_path else '/homepage/homepage/'
        return HttpResponseRedirect(reverse('user:login', kwargs={'r_path': r_path}))


def login(request, r_path='/homepage/homepage/'):
    if request.method == 'GET':

        return render(request, 'user/user_login.html', {'r_path': r_path})

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')
        rpath = request.POST.get('r_path')

        try:
            user = UserModel.objects.get(user_name=username)
        except Exception as e:
            return render(request, 'user/user_login.html', {'name_result': '用户名不存在'})

        if not check_password(password, user.password):
            return render(request, 'user/user_login.html', {'password_result': '密码错误'})

        choice_str = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
        ticket = 'TK_'
        for _ in range(12):
            ticket += choice(choice_str)
        ticket += str(int(time()))

        http_respon = HttpResponseRedirect(rpath)
        http_respon.set_cookie('ticket', ticket, max_age=3600)

        TicketModel.objects.create(
            ticket=ticket,
            user_id=user.id,
            create_time=int(time()),
        )

        return http_respon


class CheckUser(mixins.RetrieveModelMixin,
                mixins.ListModelMixin,
                viewsets.GenericViewSet):

    queryset = UserModel.objects.all()
    serializer_class = UserSerializer
    filter_class = UserFilter


def logout(request):

    if request.method == 'GET':

        response = HttpResponseRedirect('/mine/mine/')
        response.delete_cookie('ticket')

        return response

BeeQuick/BeeQuick_proj/templates/user/base_user.html
{% extends 'base.html' %}
{% load static %}
{% block extCSS %}
    <link rel="stylesheet" href="{% static 'app/user/css/user.css'  %}">
{% endblock %}

{% block EXTJS %}
    <script type="text/javascript" src="{% static 'js/md5.js' %}"></script>
{% endblock %}

BeeQuick/BeeQuick_proj/templates/user/user_login.html
{% extends 'user/base_user.html' %}
{% load static %}

{% block EXTJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'app/user/js/user_login.js' %}"></script>
{% endblock %}


{% block content %}

    <div class="container">

        <form method="post" action="" onsubmit="
        {#return check_input()#}
">
            {% csrf_token %}
            <input type="hidden" name="r_path" value="{{ r_path }}">
            <div class="form-group">
                <label for="exampleInputEmail1">用户</label>
                <input type="text" name="username" class="form-control" placeholder="用户名">
            </div>

            <div class="form-group">
                <label for="exampleInputPassword1">密码</label>
                <input id="password" type="password" name="password" class="form-control" placeholder="密码">
            </div>

            <span id="username_info">{{ name_result }}</span>
            <span id="username_info">{{ password_result }}</span>
            <input type="submit" class="btn btn-success btn-block" value="登录">
        </form>
        <p></p>
        <a href="{% url 'user:regist' r_path %} " class="btn btn-success btn-block">注册</a>

    </div>



{% endblock %}

BeeQuick/BeeQuick_proj/templates/user/user_register.html
{% extends 'user/base_user.html' %}
{% load static %}

{% block EXTJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'app/user/js/user_register.js' %}"></script>
{% endblock %}


{% block content %}

    <div class="container">

        <form method="post" action="" enctype="multipart/form-data" onsubmit="
        {#return check_input()#}
">
            {% csrf_token %}
            <input type="hidden" name="r_path" value="{{ r_path }}">
            <div class="form-group">
                <label for="exampleInputEmail1">用户</label>
                <input id="username" type="text" name="username" class="form-control" placeholder="用户名">
                <span id="username_info">{{ name_result }}</span>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="邮箱">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">密码</label>
                <input id="password" type="text" name="password" class="form-control" placeholder="密码">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">确认密码</label>
                <input id="password_confirm" type="text" class="form-control" placeholder="确认密码">
                <span id="password_confirm_info"></span>
            </div>
            <div class="form-group">
                <label for="exampleInputFile">头像</label>
                <input name="icon" type="file">
            </div>

            <input type="submit" class="btn btn-success btn-block" value="注册">
        </form>


    </div>



{% endblock %}