BeeQuick/BeeQuick_proj/BeeQuick_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.static import serve

from . import settings
from home_page import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^static/(?P<path>.*)', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^$', views.show_homepage),
    url(r'^homepage/', include('home_page.urls', namespace='home')),
    url(r'^quickbuy/', include('quick_buy.urls', namespace='quickbuy')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^mine/', include('mine.urls', namespace='mine')),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^order/', include('order.urls', namespace='order')),
]

from . import settings

from django.contrib.staticfiles.urls import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BeeQuick/BeeQuick_proj/mine/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^mine/$', views.mine, name='mine'),
]

BeeQuick/BeeQuick_proj/order/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(r'^createorder/', views.create_order, name='createorder'),
    url(r'^topay/(\d+)/', views.to_pay, name='topay'),
    url(r'^changeorderstatus/', views.change_order_status, name='changeorderstatus'),
    url(r'^order_pay/', views.order_pay, name='pay'),
    url(r'^order_wait/', views.order_wait, name='wait'),
]

BeeQuick/BeeQuick_proj/users/urls.py
from django.conf.urls import url
from rest_framework import routers

from . import views

router = routers.SimpleRouter()
router.register(r'checkuser', views.CheckUser)

urlpatterns = [

    url(r'^login/(?P<r_path>.+)', views.login, name='login'),
    url(r'^regist/(.*)', views.regist, name='regist'),
    url(r'^logout/', views.logout, name='logout'),
]

urlpatterns += router.urls

BeeQuick/BeeQuick_proj/mine/models.py
from django.db import models

# Create your models here.

BeeQuick/BeeQuick_proj/mine/views.py
from django.shortcuts import render


def mine(request):

    if request.method == 'GET':
        user = request.user
        try:
            orders = user.ordermodel_set.all()
        except:
            pay_num = 0
            wait_num = 0
        else:
            pay_num = len(orders.filter(o_status=0))
            wait_num = len(orders.filter(o_status=1))

        return render(request, 'mine/mine.html', {'pay_num': pay_num, 'wait_num': wait_num})

BeeQuick/BeeQuick_proj/templates/mine/mine.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'app/mine/mine.css' %}">
{% endblock %}

{% block EXTJS %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'app/mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}

    <div id="mine">

        <div class="fixed">
            <!--如果登录，展示头像-->
            {% if user.id %}
                <img src="/media/{{ user.icon }}" alt="icon">
            <!--或者-->
            {% else %}
                <span class="glyphicon glyphicon-user"></span>
            {% endif %}
            <!--判断结束-->

            <!--如果登录，展示姓名-->
            {% if user.id %}
                <p>{{ user.user_name }}</p>
            <!--或者展示登录的链接-->
            {% else %}
                <a href="{% url 'user:login' '/mine/mine/'%}">登录</a>
            {% endif %}
            <!--判断结束-->



            <p><span class="glyphicon glyphicon-fire"></span><span>等级</span></p>
            <!--如果没有登录,展示注册信息-->
            {% if not user.id %}
                <div id="regis">
                    <a href="">注册</a>
                </div>
            {% endif %}
            <!--判断结束-->

            <p><span class="glyphicon glyphicon-heart"></span><span>收藏</span></p>

        </div>

        <div class="mine">

            <p>我的订单<a href="#">更多&gt;</a></p>

            <div id="nav">

                <ul>
                    <li>
{#                        <a href="{% url 'order:pay' %}">#}
                        <dl>
                            <dt><span id="wait_pay_list" class="glyphicon glyphicon-usd"></span>
                                <span class="badge">
                                    <!--代付款的数量-->
                                    {% if user.id %}
                                    {{ pay_num }}
                                    {% endif %}
                                </span></dt>
                            <dd>待付款</dd>
                        </dl>
{#                        </a>#}
                    </li>
                    <li>
{#                        <a href="{% url 'order:wait' %}">#}
                        <dl>
                            <dt><span id="order_payed_list" class="glyphicon glyphicon-envelope"></span>
                                <span class="badge">
                                    <!--待收货的数量-->
                                    {% if user.id %}
                                    {{ wait_num }}
                                    {% endif %}
                                </span></dt>
                            <dd>待收货</dd>
                        </dl>
{#                        </a>#}
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-pencil"></span></dt>
                            <dd>待评价</dd>
                        </dl>

                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-retweet"></span></dt>
                            <dd>退款/售后</dd>
                        </dl>

                    </li>

                </ul>

            </div>

            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-bullhorn"></span></dt>
                            <span>积分商城</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-credit-card"></span></dt>
                            <span>优惠券</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-import"></span></dt>
                            <span>收货地址</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-phone-alt"></span></dt>
                            <span>客户反馈</span>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt><span class="glyphicon glyphicon-certificate"></span></dt>
                            <span>关于我们</span>
                        </dl>
                    </li>
                </ul>
            </menu>

            <!--如果登录了,则退出展示-->

                <p class="logout">
                    <a href="{% url 'user:logout' %}">退出</a>
                </p>
            <!--判断结束-->
        </div>
    </div>


{% endblock %}
