BeeQuick/BeeQuick_proj/BeeQuick_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.static import serve

from . import settings
from home_page import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^static/(?P<path>.*)', serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^$', views.show_homepage),
    url(r'^homepage/', include('home_page.urls', namespace='home')),
    url(r'^quickbuy/', include('quick_buy.urls', namespace='quickbuy')),
    url(r'^carts/', include('carts.urls', namespace='carts')),
    url(r'^mine/', include('mine.urls', namespace='mine')),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^order/', include('order.urls', namespace='order')),
]

from . import settings

from django.contrib.staticfiles.urls import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BeeQuick/BeeQuick_proj/carts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^carts/$', views.show_carts, name='carts'),
    url(r'^subgoods/', views.sub_goods, name='sungoods'),
    url(r'^addgoods/', views.add_goods, name='addgoods'),
    url(r'^change_select/$', views.change_select, name='change_select'),
    url(r'^change_all', views.change_all, name='change_all'),
]

BeeQuick/BeeQuick_proj/mine/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^mine/$', views.mine, name='mine'),
]

BeeQuick/BeeQuick_proj/order/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(r'^createorder/', views.create_order, name='createorder'),
    url(r'^topay/(\d+)/', views.to_pay, name='topay'),
    url(r'^changeorderstatus/', views.change_order_status, name='changeorderstatus'),
    url(r'^order_pay/', views.order_pay, name='pay'),
    url(r'^order_wait/', views.order_wait, name='wait'),
]

BeeQuick/BeeQuick_proj/carts/models.py
from django.db import models

from goods.models import GoodModel
from users.models import UserModel


class CartModel(models.Model):
    # 购物车
    user = models.ForeignKey(UserModel)  # 用户
    goods = models.ForeignKey(GoodModel)  # 商品
    c_num = models.IntegerField(default=1)  # 商品个数
    is_select = models.BooleanField(default=True)  # 是否选择商品

    class Meta:
        db_table = 'tb_carts'

BeeQuick/BeeQuick_proj/carts/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from carts.models import CartModel


def show_carts(request):

    if request.method == 'GET':

        user = request.user
        path = request.path
        ticket = request.COOKIES.get('ticket')

        if not user.id or not ticket:
            return HttpResponseRedirect(reverse('user:login', kwargs={'r_path': path}))

        carts = user.cartmodel_set.all()
        result = {
            'carts': carts,
            'select_all': 1,
        }
        for cart in carts:
            if not cart.is_select:
                result['select_all'] = 0
                break

        result = set_total(carts, result)

        return render(request, 'cart/cart.html', result)


def sub_goods(request):

    if request.method == 'POST':

        data = {
            'code': 200,
            'msg': '请求成功',
        }

        cart_id = request.POST.get('cart_id')
        user = request.user
        if not user.id:
            data = set_need_login(data)
            return JsonResponse(data)

        carts = CartModel.objects.all()
        try:
            cart = carts.get(id=cart_id, user_id=user.id)
        except Exception as e:
            data['c_num'] = 0
            return JsonResponse(data)

        if cart.c_num == 1:
            cart.delete()
            data = cart_is_none(data, '商品已移除')
        else:
            cart.c_num -= 1
            cart.save()
            data['c_num'] = cart.c_num

        data = set_total(carts, data)

        return JsonResponse(data)


def add_goods(request):

    if request.method == 'POST':

        data = {
            'code': 200,
            'msg': '请求成功',
        }

        cart_id = request.POST.get('cart_id')
        user = request.user
        if not user.id:
            data = set_need_login(data)
            return JsonResponse(data)

        carts = CartModel.objects.all()
        cart = carts.filter(id=cart_id, user_id=user.id)
        if cart.exists():
            cart = cart[0]
            cart.c_num += 1
            cart.save()
            data['c_num'] = cart.c_num
        else:
            data = cart_is_none(data, '订单不存在')

        data = set_total(carts, data)

        return JsonResponse(data)


def change_select(request):

    if request.method == 'POST':

        result = {
            'code': 200,
            'msg': '请求成功',
            'select_all': 1,
        }

        cart_id = request.POST.get('cart_id')
        carts = CartModel.objects.all()
        cart = carts.filter(id=cart_id)

        if not request.user.id:
            result = set_need_login(result)
            return JsonResponse(result)

        if cart:
            is_select = cart[0].is_select
            is_select = not is_select
            cart[0].is_select = is_select
            cart[0].save()
            result['is_select'] = is_select

        else:
            result = cart_is_none(result, '订单不存在')

        for car in carts:
            if not car.is_select:
                result['select_all'] = 0
                break
        result = set_total(carts, result)

        return JsonResponse(result)


def change_all(request):

    if request.method == 'POST':

        result = {
            'code': 200,
            'msg': '请求成功',
        }

        is_select = request.POST.get('is_select')
        user = request.user

        if not user.id:
            result = set_need_login(result)
            return JsonResponse(result)

        carts = CartModel.objects.filter(user_id=user.id)
        for cart in carts:
            cart.is_select = int(is_select)
            cart.save()

        result = set_total(carts, result)

        result['select_all'] = int(is_select)

        return JsonResponse(result)


def set_total(carts, result):
    result['total'] = 0.0
    for cart in carts:
        if cart.is_select:
            result['total'] += float(cart.goods.prefer_price) * int(cart.c_num)

    result['total'] = '%.2f' % result['total']

    return result


def set_need_login(result):
    result['code'] = 400
    result['msg'] = '请先登录'

    return result


def cart_is_none(result, msg):
    result['code'] = 201
    result['msg'] = msg

    return result

BeeQuick/BeeQuick_proj/templates/cart/cart.html
{% extends 'base_main.html' %}
{% load static %}
{% block extCSS %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'app/cart/cart.css' %}">
{% endblock %}

{% block EXTJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'app/cart/js/cart.js' %}"></script>
    <script src="{% static 'app/cart/js/common.js' %}"></script>
    <script src="{% static 'app/cart/js/change_select.js' %}"></script>
{% endblock %}


{% block content %}

    <div id="cart">

        <h3>购物车</h3>

        <div class="full">

            <section class="clear">

                <ul>
                    <li>收货人:王帅帅<div><p><span><a href="#">修改&gt;</a></span></p></div></li>
                    <li>电话:8008208820 </li>
                    <li>收货地址:宝胜北里西区28号天丰利商城</li>

                </ul>


                <div class="bill">

                    <p>闪送超市</p>

                    <a href="#">凑单专区</a>

                    <p>满100减99</p>

                </div>

                <p class="delivery">

                    <span>收货时间:</span>
                    <span>一小时送达</span>
                    <a href="#">可送达&gt;</a>
                </p>

                <p class="delivery">
                    <span>留言:</span>
                    <input type="text" placeholder="有什么特殊需求">
                </p>


                <menu>

                    <ul>
                        <!--购物车信息展示-->
                        {% for cart in carts %}
                            <li class="menuList" cartid="">
                                <div class="confirm">
                                    <span class="is_choose" is_select="">
                                            <span id="select_{{ cart.id }}" onclick="changSelect({{ cart.id }})">
                                                {% if cart.is_select %}
                                                √
                                                {% else %}
                                                    &nbsp;
                                                {% endif %}
                                            </span>
                                    </span>
                                </div>
                                <a href="#">
                                    <img src="{{ cart.goods.product_img }}" alt="">
                                    <p>{{ cart.goods.product_long_name }}</p>
                                </a>
                                <section>
                                    {% csrf_token %}
                                    <button onclick="subshop({{ cart.id }})">-</button>
                                    <span id="num_{{ cart.id }}">{{ cart.c_num }}</span>
                                    <button onclick="addshop({{ cart.id }})">+</button>
                                </section>
                            </li>
                        {% endfor %}
                        <!--购物车数据处理结束-->


                        <li class="payTheBill">

                            <div class="confirm" id="all_select">
                                <span>

                                        <span id="sele_all" onclick="changeAll({{ select_all }})">
                                            {% if select_all %}
                                                √
                                            {% else %}
                                                &nbsp;
                                            {% endif %}
                                        </span>

                                </span>
                            </div>

                            <p>
                                <span>全选</span>
                                <span id="total">总价:{{ total }}</span>
                            </p>

                            <span id="generate_order" ><a href="{% url 'order:createorder' %}">下单</a></span>

                        </li>

                    </ul>

                </menu>

{#            <div class="menuList">#}
{##}
{#                {% for cart in carts %}#}
{##}
{#                    <div class="confirm">#}
{#                    <span>#}
{#                        <span>√</span>#}
{#                    </span>#}
{#                    </div>#}
{##}
{#                    <a href="#">#}
{#                        <img src="{{ cart.goods.productimg }}" alt="{{ cart.goods.productlongname }}">#}
{#                        <p>{{ cart.goods.productlongname }}</p>#}
{#                    </a>#}
{##}
{#                {% endfor %}#}
{##}
{##}
{#            </div>#}
            </section>



        </div>


    </div>


{% endblock %}